### ISSUE TITLE
no RBAC for rollouts

### ISSUE THREAD

**Issue by cskinfill** [scalyr/helm-scalyr#56]
The scalyr agent now supports argo rollouts BUT the helm chart doesn't properly setup the clusterrole to allow access to rollouts.

```
ERROR [monitor:kubernetes_monitor] [scalyr_agent.builtin_monitors.kubernetes_monitor:1580] An error of type perm_error was seen when warming container 67ee3037d3db697eb4dd577ee749b04434f3ae059d782847a8faa793fa5538dd.  Exception was You don't have permission to access /apis/argoproj.io/v1alpha1/namespaces/default/rollouts/service1.  Please ensure you have correctly configured the RBAC permissions for the scalyr-agent's service account: Traceback (most recent call last):
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/builtin_monitors/kubernetes_monitor.py", line 1611, in run_and_propagate
    self.__k8s_cache.pod(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 1625, in pod
    return self._pods_cache.lookup(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 802, in lookup
    result = self._update_object(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 655, in _update_object
    result = self._processor.process_object(k8s, obj, query_options=query_options)
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 954, in process_object
    controller = self._get_controller_from_owners(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 917, in _get_controller_from_owners
    parent_controller = self._controllers.lookup(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 802, in lookup
    result = self._update_object(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 654, in _update_object
    obj = k8s.query_object(kind, namespace, name, query_options=query_options)
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 2293, in query_object
    return self.query_api_with_retries(
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 2023, in query_api_with_retries
    return self.query_api(query)
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/monitor_utils/k8s.py", line 2204, in query_api
    raise K8sApiAuthorizationException(
scalyr_agent.monitor_utils.k8s.K8sApiAuthorizationException: You don't have permission to access /apis/argoproj.io/v1alpha1/namespaces/default/rollouts/service1.  Please ensure you have correctly configured the RBAC permissions for the scalyr-agent's service account
```

**Comment by weilliu** [comment]
@cskinfill  Apologies for the late response. I just opened an internal ticket for engineering to fix the permission issue. We will let you know once the fix becomes available.

**Comment by weilliu** [comment]
@cskinfill  The permission issue should now be fixed. Please verify it in the latest release.
 
https://github.com/scalyr/helm-scalyr/pull/59
https://github.com/scalyr/scalyr-agent-2/pull/1125 

If you have any other questions, feel free to reach out to us via support@dataset.com
